import bus from "../Assets/bus.png";

let all_product = [
  {
    id: 1,
    name: "Aarav Sharma",
    category: "uttarpradesh",
    image: "bus.png.png",
    start_point: "Lucknow",
    end_point: "Kanpur",
    bus_address: "DL 5S CT 6587",
  },
  {
    id: 2,
    name: "Arjun Singh",
    category: "uttarpradesh",
    image: "bus.png",
    start_point: "Varanasi",
    end_point: "Agra",
    bus_address: "MH 12 AB 1234",
  },
  {
    id: 3,
    name: "Amit Kumar",
    category: "uttarpradesh",
    image: "bus.png",
    start_point: "Allahabad",
    end_point: "Lucknow",
    bus_address: "UP 14 CD 5678",
  },
  {
    id: 4,
    name: "Ananya Verma",
    category: "uttarpradesh",
    image: "bus.png",
    start_point: "Kanpur",
    end_point: "Varanasi",
    bus_address: "RJ 45 EF 9012",
  },
  {
    id: 5,
    name: "Aarush Gupta",
    category: "uttarpradesh",
    image: "bus.png",
    start_point: "Agra",
    end_point: "Lucknow",
    bus_address: "MP 67 GH 3456",
  },
  {
    id: 6,
    name: "Aryan Singh",
    category: "uttarpradesh",
    image: "bus.png",
    start_point: "Ghaziabad",
    end_point: "Kanpur",
    bus_address: "TN 89 IJ 6789",
  },
  {
    id: 7,
    name: "Avani Yadav",
    category: "uttarpradesh",
    image: "bus.png",
    start_point: "Meerut",
    end_point: "Noida",
    bus_address: "KL 01 KL 4321",
  },
  {
    id: 8,
    name: "Aditya Singh",
    category: "uttarpradesh",
    image: "bus.png",
    start_point: "Gorakhpur",
    end_point: "Lucknow",
    bus_address: "KA 23 MN 8765",
  },
  {
    id: 9,
    name: "Akshara Tiwari",
    category: "uttarpradesh",
    image: "bus.png",
    start_point: "Jhansi",
    end_point: "Kanpur",
    bus_address: "AP 78 QR 2345",
  },
  {
    id: 10,
    name: "Abhinav Mishra",
    category: "uttarpradesh",
    image: "bus.png",
    start_point: "Aligarh",
    end_point: "Varanasi",
    bus_address: "TS 45 UV 5678",
  },
  {
    id: 11,
    name: "Aishwarya Singh",
    category: "uttarpradesh",
    image: "bus.png",
    start_point: "Moradabad",
    end_point: "Lucknow",
    bus_address: "DL 67 OP 9012",
  },
  {
    id: 12,
    name: "Aniket Verma",
    category: "uttarpradesh",
    image: "bus.png",
    start_point: "Saharanpur",
    end_point: "Kanpur",
    bus_address: "UP 89 QR 3456",
  },
  {
    id: 13,
    name: "Rahul Kumar",
    category: "haryana",
    image: "bus.png",
    start_point: "Gurgaon",
    end_point: "Faridabad",
    bus_address: "HR 12 ST 6789",
  },
  {
    id: 14,
    name: "Riya Sharma",
    category: "haryana",
    image: "bus.png",
    start_point: "Panipat",
    end_point: "Rohtak",
    bus_address: "PB 34 UV 1234",
  },
  {
    id: 15,
    name: "Rohit Yadav",
    category: "haryana",
    image: "bus.png",
    start_point: "Ambala",
    end_point: "Karnal",
    bus_address: "HR 56 WX 5678",
  },
  {
    id: 16,
    name: "Ritu Gupta",
    category: "haryana",
    image: "bus.png",
    start_point: "Hisar",
    end_point: "Panipat",
    bus_address: "PB 78 YZ 9012",
  },
  {
    id: 17,
    name: "Rishabh Singh",
    category: "haryana",
    image: "bus.png",
    start_point: "Sirsa",
    end_point: "Gurgaon",
    bus_address: "HR 23 AB 2345",
  },
  {
    id: 18,
    name: "Radha Verma",
    category: "haryana",
    image: "bus.png",
    start_point: "Yamunanagar",
    end_point: "Ambala",
    bus_address: "HR 45 CD 6789",
  },
  {
    id: 19,
    name: "Raj Kumar",
    category: "haryana",
    image: "bus.png",
    start_point: "Bhiwani",
    end_point: "Kurukshetra",
    bus_address: "HR 67 EF 1234",
  },
  {
    id: 20,
    name: "Riyaan Singh",
    category: "haryana",
    image: "bus.png",
    start_point: "Palwal",
    end_point: "Jind",
    bus_address: "HR 89 GH 5678",
  },
];

export default all_product;
